DROP TABLE IF EXISTS polynomial_calculates;
DROP TABLE IF EXISTS polynomials;

CREATE TABLE polynomials (
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polynomial VARCHAR(255)
);

CREATE TABLE polynomial_calculates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    polynomial_id INTEGER NOT NULL,
    value       INTEGER NOT NULL,
    result        DOUBLE NOT NULL,
    UNIQUE (polynomial_id, value),
    FOREIGN KEY (polynomial_id) REFERENCES polynomials(id)
);
