CREATE TABLE IF NOT EXISTS polynomials (
    id         INTEGER NOT NULL,
    polynomial VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS polynomial_calculates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    polynomial_id INTEGER NOT NULL,
    value         INTEGER NOT NULL,
    result        FLOAT(53) NOT NULL,
    primary key (id)
);

ALTER TABLE polynomial_calculates DROP CONSTRAINT IF EXISTS unique_index_polynomialId_value;
ALTER TABLE IF EXISTS polynomial_calculates ADD CONSTRAINT unique_index_polynomialId_value UNIQUE (polynomial_id, value);
ALTER TABLE IF EXISTS polynomial_calculates ADD CONSTRAINT fk_polynomial_id FOREIGN KEY (polynomial_id) references polynomials;